services:
  - type: web
    name: wiwave-radar
    env: python
    buildCommand: pip install -r requirements.txt && cd frontend && npm ci && npm run build
    startCommand: python server.py
    envVars:
      - key: SIMULATION_MODE
        value: "true"
      - key: ENVIRONMENT
        value: production
      - key: WIWAVE_HOST
        value: "0.0.0.0"
      - key: PYTHON_VERSION
        value: 3.10.0
